### PR TITLE
small fix to XRSession.end()

### PR DESCRIPTION
**Pull request by blairmacintyre**
typo: this.immersive should be this[PRIVATE].immersive

### CODE REVIEW

**Comment by jsantell** [comment]
Once the build flies are removed from the commit, LGTM!

**Comment by blairmacintyre** [comment]
Oh, we don’t include the builds?  How do they get rebuilt?

---
Blair MacIntyre
Principal Research Scientist

snt frm iOS kybrd, pls pardon typos and weird auto-corrections

blairmacintyre.me && pronoun.is/he/him

________________________________

**Comment by jsantell** [comment]
> Oh, we don’t include the builds? How do they get rebuilt?


As a separate commit -- generally I don't merge any minified/artifact code since it's unverifiable with possibly different dependencies or changes, or worse, malicious code. Of course I trust you Blair :smile: and it's a great question that hasn't been revisited since this project was very much in its infancy. While I still don't think PRs should be accepted with built artifacts for that reason, building becomes a bottleneck (someone has to build/commit manually), and now that Github actions are available, it might be a good time to revisit. An action could build/commit on every commit if that's desirable, or possibly is it still necessary to commit an artifact to git history, etc.

I have a slight preference towards only committing the artifact on version releases, but haven't thought much about it, and publishing practices seem to change frequently.

**Comment by blairmacintyre** [comment]
Totally makes sense on the builds.

Anyway, I removed them.

**Comment by jsantell** [comment]
Thank you @blairmacintyre! I'll open up an issue for discussion on some sort of build automation w/r/t the current topic as well

**Pull request merged**
