### PR TITLE
make XRWebGLLayer spec compliant

### LINKED ISSUE #167: Polyfilled XRWebGLLayer is not spec compliant
The [XRWebGLLayer spec](https://www.w3.org/TR/webxr/#xrwebgllayer-interface) mentions:

> If session is an [immersive session](https://www.w3.org/TR/webxr/#immersive-session) and context’s [XR compatible](https://www.w3.org/TR/webxr/#xr-compatible) boolean is false, throw an [InvalidStateError](https://webidl.spec.whatwg.org/#invalidstateerror) and abort these steps.

In [the current implementation](https://github.com/immersive-web/webxr-polyfill/blob/fafd43da6ce49dd86d7cf8d94ff69a6cca593f9b/src/api/XRWebGLLayer.js#L55), an  InvalidStateError is thrown when the XR compatible boolean is set to false regardless of whether or not the session is an immersive session. 

This makes a progressive enhancement experience as mentioned in the [WebXR explainer](https://immersive-web.github.io/webxr/explainer.html#setting-up-an-xrwebgllayer) not possible. When creating a context without the XR compatible boolean set, it should still be usable in an inline session.

### PR DESCRIPTION
**Pull request by AAwouters**
Fixes #167 

[Relevant spec change](https://github.com/immersive-web/webxr/commit/841e8f7d24ce8cefbfc09d49aef76c2c824d3fb4)

### CODE REVIEW

**Comment by matthargett** [comment]
Can you add a unit test?

**Comment by ceyhun-o** [comment]
Can this PR be reviewed? What is needed to merge this?

**Review by toji — APPROVED** [review]
Change looks fine. It would be good to add a unit tests as previously requested.

**Comment by MattiasBuelens** [comment]
@AAwouters worked on this during his internship at @THEOplayer. I'm happy to take over this PR if needed.

> Change looks fine. It would be good to add a unit tests as previously requested.

We looked at the unit tests, but they are *completely broken*. They haven't been touched since 2018 in https://github.com/immersive-web/webxr-polyfill/commit/39289985c085133fbf729c3a16637f70e5c213c3, and I suspect no-one has tried running them since then. I tried running `npm test` locally, but I didn't get very far:
* https://github.com/immersive-web/webxr-polyfill/commit/fa824a9e79b2bf101512b6c72432037bd9758a30 moved `XRDevice.js` from `src/api/` to `src/devices/`, but did not update the imports inside the tests ([1](https://github.com/immersive-web/webxr-polyfill/blob/fafd43da6ce49dd86d7cf8d94ff69a6cca593f9b/test/api/test-xr-device.js#L19), [2](https://github.com/immersive-web/webxr-polyfill/blob/fafd43da6ce49dd86d7cf8d94ff69a6cca593f9b/test/api/test-xr-device-pose.js#L19), [3](https://github.com/immersive-web/webxr-polyfill/blob/fafd43da6ce49dd86d7cf8d94ff69a6cca593f9b/test/lib/utils.js#L16)). It also changed the API of `XRDevice.requestSession({ immersive, outputContext })` to `XRDevice.requestSession(mode)`, but [test-xr-device.js](https://github.com/immersive-web/webxr-polyfill/blob/fafd43da6ce49dd86d7cf8d94ff69a6cca593f9b/test/api/test-xr-device.js#L47) still uses the old API.
* https://github.com/immersive-web/webxr-polyfill/commit/d04ca99bb3a1805a08f6f6d4449cf76a16cb31c2 renamed `XRDevicePose` to `XRViewerPose`, but again failed to update the tests ([1](https://github.com/immersive-web/webxr-polyfill/blob/fafd43da6ce49dd86d7cf8d94ff69a6cca593f9b/test/api/test-xr-device-pose.js#L21)).

I don't currently have the bandwidth to fix all of these tests.

**Pull request merged**
