### PR TITLE
Event subclass fix ios

### PR DESCRIPTION
**Pull request by blairmacintyre**
This is the code that fixes issue #130

### CODE REVIEW

**Comment by jsantell** [comment]
I misunderstood in #130, I'm following you now -- found more info (or at least the same problem) [here](https://stackoverflow.com/a/58471803); happy that this works! Could you squash this down to one commit? I'll merge it in then. Thank you!

**Comment by blairmacintyre** [comment]
pretend I'm a git noob (not a stretch);  how do I squash to a single commit? :)

**Comment by jsantell** [comment]
> pretend I'm a git noob (not a stretch); how do I squash to a single commit? :)

I use a shortcut `git rebase -i HEAD~$1` where $1 is how many previous commits you'd like to squash -- then squash all commits except the top one (could be any commit really), and modify the final commit message. As is all things git, not sure if this is the correct way, but just the magical incantation I've internalized :smile:

**Comment by blairmacintyre** [comment]
I can't get it to work ... I seem to keep adding empty commits ... I'm just going to close this, it's a mess.

**Comment by blairmacintyre** [comment]
@jsantell I gave up on figuring out my git incompetance and just submitted a new PR #135

**Pull request closed without merging**
